apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: order-service
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "1280Mi"
            cpu: "500m"
        ports:
        - containerPort: 9002
        env:
          - name: BPL_JVM_THREAD_COUNT
            value: "50"
          - name: SPRING_R2DBC_URL
            value: jdbc:postgresql://polar-postgres/polardb_order
          - name: SPRING_FLYWAY_URL
            value: jdbc:postgresql://polar-postgres/polardb_order
        lifecycle:
            preStop:                    
              exec: 
                command: [ "sh", "-c", "sleep 5" ] 
